# Generated by Django 5.2.17 on 2026-09-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('playing', 'Playing'), ('paused', 'Paused'), ('game_over', 'Game Over'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('stage', models.IntegerField(default=0)),
                ('monster', models.IntegerField(default=0)),
                ('enemy_number', models.IntegerField(default=0)),
                ('difficulty', models.CharField(blank=True, default='', max_length=30)),
                ('hp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_status', to='student.student')),
            ],
        ),
    ]
