# Generated by Django 5.2.17 on 2026-09-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_gamestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='status',
            field=models.CharField(default='not_started', max_length=20),
        ),
    ]
